name = input()
city = input()
aqi = int(input())
pm25 = float(input())
pm10 = float(input())
temp = float(input())
humidity = float(input())
print(f"Station: {name}")
print(f"City: {city}")
print(f"AQI: {aqi}")
print(f"PM2.5: {pm25}")
print(f"PM10: {pm10}")
print(f"Temp: {temp}")
print(f"Humidity: {humidity}")